/**
 * @file trackingmanager.h
 * @brief Coordinates multi-worm tracking, video processing, and cross-thread orchestration.
 *
 * Responsibilities:
 *  - Orchestrate end-to-end tracking: initial video processing, per-worm trackers (forward/backward),
 *    frame-atomic merge/split handling, progress aggregation, and finalization.
 *  - Own/coordinate worker threads (video processing, per-worm tracking, optional video saving).
 *  - Persist run metadata (threshold settings, input blobs) and populate merge history in storage.
 *
 * Threading model:
 *  - GUI thread constructs and connects to TrackingManager.
 *  - Video processing workers run on QThreads (chunked).
 *  - Per-worm trackers (forward/backward) run on QThreads.
 *  - Optional VideoSaverWorker runs on a background QThread.
 *  - Cross-thread communication via queued signals/slots; registerMetaTypes() registers custom types.
 *
 * Lifecycle:
 *  - startFullTrackingProcess(...) initializes and launches workers.
 *  - cancelTracking() requests cooperative stop.
 *  - cleanupThreadsAndObjects() joins/cleans workers and clears transient state.
 *  - Emits trackingFinishedSuccessfully(...), trackingCancelled(), or trackingFailed(QString) on terminal states.
 *
 * Key signals:
 *  - overallTrackingProgress(int) — aggregate percent.
 *  - trackingStatusUpdate(QString) — human-readable status (e.g., chunk x/y, saving n%).
 *  - allTracksUpdated(Tracking::AllWormTracks) — incremental consolidated tracks.
 *  - trackingFinishedSuccessfully(QString), trackingFailed(QString), trackingCancelled().
 *
 * Key data structures:
 *  - FrameSpecificPhysicalBlob — per-frame merged-blob record used for merge/split logic.
 *  - m_frameMergeRecords, m_splitResolutionMap — per-frame maps for merge/split tracking.
 *  - m_wormObjectsMap, m_wormTrackersList — track history ownership and live workers.
 */
 // trackingmanager.h
#ifndef TRACKINGMANAGER_H
#define TRACKINGMANAGER_H

#include <QObject>
#include <QList>
#include <QMap>
#include <QString>
#include <QRectF>
#include <QThread>
#include <QSet>
#include <QMutex>
#include <QDateTime>
#include <QPointer>
#include <QDir>
#include <QFileInfo>
#include <QJsonDocument>
#include <QJsonObject>

#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>

#include "../data/trackingcommon.h"
#include "../data/wormobject.h"
#include "processing/videoprocessor.h" // For VideoProcessor type, not direct instantiation here
#include "wormtracker.h"    // For WormTracker type and enums
#include "../data/trackingdatastorage.h" // Central data storage

// Constants for matching physical blobs on a frame
// PHYSICAL_BLOB_IOU_THRESHOLD:
//   IoU threshold used to decide whether two bounding boxes (on the same frame) represent the
//   same physical merged blob. Higher values reduce false-positive merges but may split legitimate
//   merged blobs. Tune cautiously; affects merge history and split resolution.
// PHYSICAL_BLOB_CENTROID_MAX_DIST_SQ:
//   Squared pixel distance threshold between centroids to consider blobs as the same physical
//   object on a frame. Kept squared to avoid costly sqrt; e.g., 100.0 ~= 10px radius.
//   Used as a secondary check alongside IoU to stabilize matching under small jitter.
const double PHYSICAL_BLOB_IOU_THRESHOLD = 0.5;
const double PHYSICAL_BLOB_CENTROID_MAX_DIST_SQ = 100.0;

// No longer using paused worm resolution
/**
 * @brief Per-frame record of a distinct physical blob (possibly a merge of multiple worms).
 *
 * Purpose:
 *  - Serves as the canonical representation of "what exists on this frame" independent of which
 *    WormTracker reported it first. Multiple WormTrackers may reference the same physical blob.
 *  - Enables frame-atomic merge/split reasoning by decoupling per-tracker state from per-frame observations.
 *
 * Matching criteria:
 *  - Instances are matched using IoU (PHYSICAL_BLOB_IOU_THRESHOLD) and centroid proximity
 *    (PHYSICAL_BLOB_CENTROID_MAX_DIST_SQ). A successful match indicates the same physical blob.
 *
 * Usage notes:
 *  - uniqueId is generated by TrackingManager (m_nextPhysicalBlobId) and is unique per run.
 *  - participatingWormTrackerIDs tracks all conceptual worm IDs present in the blob on this frame.
 *  - selectedByWormTrackerId indicates which tracker chose this blob post-split (if any).
 */
// Represents a distinct physical (merged) blob observed on a specific frame.
struct FrameSpecificPhysicalBlob {
    int uniqueId;                           // Globally unique ID for this physical blob instance
    QRectF currentBoundingBox;
    cv::Point2f currentCentroid;            // Centroid of currentBoundingBox
    double currentArea;
    std::vector<cv::Point> contourPoints;   // Raw contour points in video coordinates (used for merge/split logic)
    QSet<int> participatingWormTrackerIDs;  // Conceptual IDs of WormTrackers in this blob on this frame
    int frameNumber;                        // The frame this blob exists on
    int selectedByWormTrackerId;            // Which WT has selected this blob as their target (-1 = unselected)
    // QDateTime timeFirstReported;         // When this physical blob was first noted on this frame

    FrameSpecificPhysicalBlob() : uniqueId(-1), currentArea(0.0), frameNumber(-1), selectedByWormTrackerId(-1) {}
};

// No longer using pause mechanism - split resolution is immediate


// Forward declarations
class TrackingDataStorage;

/**
 * @class VideoSaverWorker
 * @brief Background worker that saves thresholded video on a separate thread.
 *
 * Receives processed frames via receiveVideoData(...), writes a video file asynchronously,
 * and reports progress/completion/failure via signals. Intended to keep the GUI responsive
 * and to reduce memory pressure by streaming out frames.
 */
class VideoSaverWorker : public QObject {
    Q_OBJECT

public:
    explicit VideoSaverWorker(QObject* parent = nullptr);

public slots:
    /**
     * @brief Receive processed frames and parameters to begin asynchronous video saving.
     * @param reversedFrames Frames from the backward pass (reverse order for output concatenation).
     * @param forwardFrames Frames from the forward pass.
     * @param outputPath Target path for the saved video file.
     * @param fps Frames per second to use for encoding.
     * @param frameSize Frame dimensions (width/height) for the output video.
     */
    void receiveVideoData(std::vector<cv::Mat> reversedFrames,
                         std::vector<cv::Mat> forwardFrames,
                         const QString& outputPath,
                         double fps,
                         cv::Size frameSize);

signals:
    /**
     * @brief Emitted when saving completes successfully.
     * @param savedVideoPath Absolute path to the saved video file.
     */
    void savingComplete(const QString& savedVideoPath);
    /**
     * @brief Emitted when saving fails.
     * @param errorMessage Human-readable error description.
     */
    void savingError(const QString& errorMessage);
    /**
     * @brief Emitted periodically to indicate save progress (0–100).
     */
    void savingProgress(int percentage);

private:
    void startSaving();
    
    std::vector<cv::Mat> m_reversedFrames;
    std::vector<cv::Mat> m_forwardFrames;
    QString m_outputPath;
    double m_fps;
    cv::Size m_frameSize;
};

class TrackingManager : public QObject {
    Q_OBJECT

public:
    /**
     * @brief Construct a TrackingManager with internally managed storage and models.
     * @param parent Optional QObject parent.
     */
    explicit TrackingManager(QObject* parent = nullptr);
    /**
     * @brief Construct a TrackingManager with external storage.
     * @param storage Pointer to central data storage (not owned if externally managed).
     * @param parent Optional QObject parent.
     */
    explicit TrackingManager(TrackingDataStorage* storage, QObject* parent = nullptr);
    /**
     * @brief Destructor. Ensures cleanup of worker threads and transient state.
     */
    ~TrackingManager();
    
    // Retracking functionality
    /**
     * @brief Get the path to the last saved thresholded video (if any).
     * @return Absolute path to the saved video or empty if none was saved.
     */
    QString getSavedVideoPath() const;
    /**
     * @brief Start a focused retracking on a pre-thresholded video segment for a specific blob.
     * @param thresholdedVideoPath Path to the pre-processed (thresholded) video.
     * @param fixBlobId Identifier of the blob/track to fix.
     * @param initialROI Initial ROI for retracking.
     * @param startFrame Start frame index (inclusive).
     * @param endFrame End frame index (exclusive).
     * @param replaceExisting Whether to replace existing track data for this blob.
     * @param extendTrack Whether to extend the existing track instead of replacing.
     * @return true if the retracking process was launched; false otherwise.
     */
    bool startRetrackingProcess(const QString& thresholdedVideoPath,
                               int fixBlobId,
                               const QRectF& initialROI,
                               int startFrame,
                               int endFrame,
                               bool replaceExisting,
                               bool extendTrack);

public slots:
    /**
     * @brief Start a full multi-worm tracking run.
     * @param videoPath Path to the source video.
     * @param dataDirectory Optional per-run data directory (metadata, outputs).
     * @param keyFrameNum Frame index chosen as the keyframe.
     * @param initialWorms Initial worm descriptors (IDs, ROIs, colors).
     * @param settings Thresholding parameters for pre-processing.
     * @param totalFramesInVideoHint Optional hint for total frames (progress/bounds).
     */
    void startFullTrackingProcess(const QString& videoPath,
                                  const QString& dataDirectory,
                                  int keyFrameNum,
                                  const std::vector<Tracking::InitialWormInfo>& initialWorms,
                                  const Thresholding::ThresholdSettings& settings,
                                  int totalFramesInVideoHint);
    /**
     * @brief Request cancellation of the current tracking run.
     *
     * Sets internal cancellation flags and asks workers to stop cooperatively.
     * A terminal signal (trackingCancelled or trackingFailed) will follow.
     */
    void cancelTracking();
    /**
     * @brief Join/clean all worker threads and clear transient state.
     *
     * Safe to call after cancel/fail or before a new run; idempotent.
     */
    void cleanupThreadsAndObjects(); // Made public slot so it can be called via QMetaObject::invokeMethod

private slots:
    // Video processing slots
    void handleInitialProcessingComplete(const std::vector<cv::Mat>& finalForwardFrames,
                                         const std::vector<cv::Mat>& finalReversedFrames,
                                         double fps,
                                         cv::Size frameSize);
    void handleVideoChunkProcessingError(int chunkId, const QString& errorMessage);
    void handleRangeProcessingProgress(int chunkId, int percentage);
    void handleRangeProcessingComplete(int chunkId,
                                       const std::vector<cv::Mat>& processedFrames,
                                       bool wasForwardChunk);

    // WormTracker slots
    void handleFrameUpdate(int reportingConceptualWormId,
                           int originalFrameNumber,
                           const Tracking::DetectedBlob& primaryBlob, // Anchor blob for track history
                           const Tracking::DetectedBlob& fullBlob,    // Full blob for merge/state processing
                           QRectF searchRoiUsed,
                           Tracking::TrackerState currentState,
                           const QList<Tracking::DetectedBlob>& splitCandidates = QList<Tracking::DetectedBlob>());
    void handleWormTrackerFinished();
    void handleWormTrackerError(int reportingConceptualWormId, QString errorMessage);
    void handleWormTrackerProgress(int reportingConceptualWormId, int percentDone);

    // Video saving slots
    void handleVideoSavingComplete(const QString& savedVideoPath);
    void handleVideoSavingError(const QString& errorMessage);

signals:
    /**
     * @brief Aggregate percent progress (0–100) across video processing and all trackers.
     */
    void overallTrackingProgress(int percentage);
    /**
     * @brief Human-readable status updates (e.g., "Processing chunk x/y", "Saving video n%").
     */
    void trackingStatusUpdate(const QString& statusMessage);
    /**
     * @brief Incremental consolidated tracks for UI/storage.
     * @param tracks Map of conceptual worm IDs to their current/complete tracks.
     */
    void allTracksUpdated(const Tracking::AllWormTracks& tracks);
    /**
     * @brief Emitted on successful completion of a run.
     * @param outputPath Optional path to a primary output (e.g., saved video), if available.
     */
    void trackingFinishedSuccessfully(const QString& outputPath);
    /**
     * @brief Emitted when the run fails irrecoverably.
     * @param reason Human-readable error explanation.
     */
    void trackingFailed(const QString& reason);
    /**
     * @brief Emitted when user/system cancellation completes.
     */
    void trackingCancelled();
    
    /**
     * @brief Send processed frames to the background video-saver worker thread.
     * @param reversedFrames Backward-direction frames (reverse order for output concatenation).
     * @param forwardFrames Forward-direction frames.
     * @param outputPath Target path for the saved video file.
     * @param fps Frames per second for encoding.
     * @param frameSize Dimensions of frames to be written.
     */
    void sendVideoDataToWorker(std::vector<cv::Mat> reversedFrames,
                              std::vector<cv::Mat> forwardFrames,
                              const QString& outputPath,
                              double fps,
                              cv::Size frameSize);


private:
    // Core logic for frame-atomic merge/split handling
    void processFrameSpecificMerge(int signedWormId, int frameNumber,
                                   const Tracking::DetectedBlob& reportedFullBlob,
                                   WormTracker* reportingTrackerInstance);
    void processFrameSpecificSplit(int signedWormId, int frameNumber,
                                   const QList<Tracking::DetectedBlob>& allSplitCandidates,
                                   const Tracking::DetectedBlob& chosenCandidate,
                                   WormTracker* reportingTrackerInstance);
    bool attemptImmediateSplitResolution(int conceptualWormId, int frameNumber, 
                                     const QList<Tracking::DetectedBlob>& allCandidates,
                                     const Tracking::DetectedBlob& chosenCandidate,
                                     WormTracker* trackerInstance);

    // Helper functions for signed worm IDs (direction-aware)
    int getSignedWormId(int conceptualWormId, WormTracker::TrackingDirection direction);
    int getUnsignedWormId(int signedWormId);
    WormTracker::TrackingDirection getDirectionFromSignedId(int signedWormId);

    // Helper and utility functions
    void launchWormTrackers();
    void updateOverallProgress();
    void checkForAllTrackersFinished();
    bool outputTracksToCsv(const Tracking::AllWormTracks& tracks, const QString& outputFileName) const;
    double calculateIoU(const QRectF& r1, const QRectF& r2) const;
    void assembleProcessedFrames(); // For parallel video processing
    size_t getProcessedVideoMemoryUsage() const; // Returns memory usage in bytes
    void clearProcessedVideoMemory(); // Clear processed video data from memory
    
    // Video saving functionality
    void startVideoSaving(); // Start background video saving process
    
    // JSON storage methods
    QString createVideoSpecificDirectory(const QString& dataDirectory, const QString& videoPath);
    void saveThresholdSettings(const QString& directoryPath, const Thresholding::ThresholdSettings& settings);
    void saveInputBlobs(const QString& directoryPath, const std::vector<Tracking::InitialWormInfo>& worms);
    bool compareThresholdSettings(const QString& filePath, const Thresholding::ThresholdSettings& currentSettings);
    QJsonObject thresholdSettingsToJson(const Thresholding::ThresholdSettings& settings) const;
    QJsonObject initialWormInfoToJson(const Tracking::InitialWormInfo& worm) const;

    // Basic tracking parameters
    QString m_videoPath;
    QString m_dataDirectory;
    QString m_videoSpecificDirectory;
    int m_keyFrameNum;
    std::vector<Tracking::InitialWormInfo> m_initialWormInfos;
    Thresholding::ThresholdSettings m_thresholdSettings;
    int m_totalFramesInVideoHint;
    bool m_isTrackingRunning;
    bool m_cancelRequested;
    bool m_isVideoSaving;

    // Video processing members (for parallel processing)
    QList<QPointer<QThread>> m_videoProcessorThreads; // One per VideoProcessor chunk worker (lifetime: run scoped)
    int m_videoProcessorsFinishedCount;
    int m_totalVideoChunksToProcess;
    QMap<int, std::vector<cv::Mat>> m_assembledForwardFrameChunks;
    QMap<int, std::vector<cv::Mat>> m_assembledBackwardFrameChunks;
    QMap<int, int> m_videoChunkProgressMap;
    std::vector<cv::Mat> m_finalProcessedForwardFrames;
    std::vector<cv::Mat> m_finalProcessedReversedFrames;
    double m_videoFps;
    cv::Size m_videoFrameSize;

    // Worm object and tracker management
    QMap<int, WormObject*> m_wormObjectsMap; // Stores track history for each conceptual worm
    QList<WormTracker*> m_wormTrackersList;  // List of active tracker instances
    QMap<int, WormTracker*> m_wormIdToForwardTrackerInstanceMap;
    QMap<int, WormTracker*> m_wormIdToBackwardTrackerInstanceMap;
    QList<QPointer<QThread>> m_trackerThreads; // One per WormTracker instance (forward/backward per conceptual worm)
    int m_expectedTrackersToFinish;
    int m_finishedTrackersCount;
    int m_videoProcessingOverallProgress;
    QMap<WormTracker*, int> m_individualTrackerProgress; // WormTracker instance -> progress %
    Tracking::AllWormTracks m_finalTracks; // Final consolidated tracks
    TrackingDataStorage* m_storage;        // Pointer to central data storage

    // --- Data structures for frame-atomic merge/split logic ---
    // m_frameMergeRecords:
    //   frame -> list of distinct physical blobs observed on that frame (FrameSpecificPhysicalBlob).
    //   This is the authoritative per-frame view used to reason about merges/splits independent of trackers.
    QMap<int, QList<FrameSpecificPhysicalBlob>> m_frameMergeRecords;

    // m_splitResolutionMap:
    //   frame -> (conceptualWormId -> chosen DetectedBlob) after a split decision for that frame.
    //   Records which physical blob each worm selected immediately post-split for reproducibility and UI overlays.
    QMap<int, QMap<int, Tracking::DetectedBlob>> m_splitResolutionMap;

    // Monotonic counter to generate unique FrameSpecificPhysicalBlob::uniqueId values per run.
    int m_nextPhysicalBlobId;

    // m_wormToPhysicalBlobIdMap:
    //   conceptualWormId -> FrameSpecificPhysicalBlob::uniqueId for the current frame.
    //   Enables quick lookups of the physical blob membership for continuity across frames.
    QMap<int, int> m_wormToPhysicalBlobIdMap;


    // Video saving members
    QPointer<QThread> m_videoSaverThread; // Background worker thread for thresholded video saving (optional)
    QString m_savedVideoPath; // Path where the thresholded video will be saved

    // General utilities
    QMutex m_dataMutex; // Protects shared data structures
    
    // Populate per-frame merge groups into TrackingDataStorage (batch write at end of tracking)
    void populateMergeHistoryInStorage();
    
    // Helper method to register meta types
    void registerMetaTypes();
};

#endif // TRACKINGMANAGER_H
